version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: v3.x
  reviewers:
  - rangerrick
  labels:
  - dependabot
  ignore:
  - dependency-name: "@types/node"
  commit-message:
    prefix: build
    include: scope
