version: 2.1

commands:
  cached-checkout:
      description: "checkout with caching"
      steps:
        - restore_cache:
            name: Restore Git Cache
            keys:
              - git-{{ .Branch }}-{{ .Revision }}
              - git-{{ .Branch }}-
              - git-
        - checkout:
            name: Check Out Code
        - run:
            name: Fetch from Git
            command: |
              git fetch origin
              git config user.name 'CircleCI Automated Commit'
              git config user.email 'github@raccoonfink.com'
        - save_cache:
            name: Save Git Cache
            key: git-{{ .Branch }}-{{ .Revision }}
            paths:
              - ".git"
  generate-changelog:
      steps:
        - run:
            name: Generate Change Log
            command: npm run changelog
  cached-npm-install:
      description: run "npm install", updating cache
      steps:
        - restore_cache:
            name: Restore Package Cache
            keys:
              - npm-packages-{{ .Branch }}-{{ checksum "package-lock.json" }}
              - npm-packages-{{ .Branch }}
              - npm-packages-
        - run:
            name: Install Node Dependencies
            command: npm --prefer-offline --no-progress ci
        - save_cache:
            name: Save Package Cache
            key: npm-packages-{{ .Branch }}-{{ checksum "package-lock.json" }}
            paths:
              - node_modules/

jobs:
  run-tests:
      docker:
        - image: circleci/node:12-browsers
          environment:
            TZ: "America/New_York"
      steps:
        - cached-checkout
        - cached-npm-install
        - run:
            name: Run Production Build
            command: npm --prefer-offline --no-progress run prep-web
        - run:
            name: Run Tests
            command: npm --prefer-offline --no-progress run test-headless
  merge-branch:
      docker:
        - image: circleci/node:12-browsers
          environment:
            TZ: "America/New_York"
      steps:
        - cached-checkout
        - run:
            name: Merge v2.x to Main
            command: |
              git fetch
              git checkout main
              git reset --hard origin/main
              git merge -m 'automated merge from v2.x -> main' --log v2.x
        - cached-npm-install
        - run:
            name: Build Artifacts
            command: npm --prefer-offline --no-progress run prep-web
        - generate-changelog
        - add_ssh_keys:
            fingerprints:
              - "8a:75:48:b0:a2:c5:9d:53:05:11:4c:bd:3f:31:b4:7a"
        - run:
            name: Commit and Push Updated Artifacts
            command: |
              git add -A
              if [ `git diff HEAD | wc -l` -gt 0 ]; then
                echo "changes detected; committing updated dist/"
                git commit -m 'build: automated merge from v2.x'
              fi
              git push origin pages:pages
  merge-pages:
      docker:
        - image: circleci/node:12-browsers
          environment:
            TZ: "America/New_York"
      steps:
        - cached-checkout
        - run:
            name: Merge v2.x to GitHub pages
            command: |
              git fetch --all
              git checkout pages
              git reset --hard origin/pages
              git merge -m 'automated merge from v2.x -> main' --log v2.x
        - cached-npm-install
        - run:
            name: Install rsync
            command: sudo apt-get update && sudo apt-get -y install rsync
        - run:
            name: Build Artifacts
            command: npm run prep-web
        - run:
            name: Sync build assets to docs/
            command: rsync -avr --delete www/ docs/
        - add_ssh_keys:
            fingerprints:
              - "8a:75:48:b0:a2:c5:9d:53:05:11:4c:bd:3f:31:b4:7a"
        - run:
            name: Commit and Push Updated Artifacts
            command: |
              git add -A
              if [ `git diff HEAD | wc -l` -gt 0 ]; then
                echo "changes detected; committing updated docs/"
                git commit -m 'build: automated merge from v2.x'
              fi
              git push origin pages:pages

workflows:
  run-tests-and-deploy:
    jobs:
      - run-tests
      - merge-branch:
          requires:
            - run-tests
          filters:
            branches:
              only:
                - v2.x
      - merge-pages:
          requires:
            - run-tests
          filters:
            branches:
              only:
                - v2.x

