version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "daily"
    default_reviewers:
      - "rangerrick"
    default_labels:
      - "dependabot"
    commit_message:
      prefix: "build"
      include_scope: true
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "semver:minor"
